default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: climber_development

test:
  <<: *default
  database: climber_test

production:
  <<: *default
  database: climber_production
